-- Ideas table for the reel generator.
-- Run this ONCE in the Supabase SQL editor:
-- https://supabase.com/dashboard/project/jszsasfibqdmtbejbybp/sql/new
--
-- Columns:
--   id              unique row id (uuid), generated by Supabase
--   "index"         position of the idea in its generated batch, starting at 1
--   title/hook/summary  the generated idea text
--   topic/tone      what was requested
--   video_generated defaults to false (no video made yet)
--   created_at      insertion time

create table if not exists public.ideas (
    id uuid primary key default gen_random_uuid(),
    "index" integer not null,
    title text not null,
    hook text,
    summary text,
    topic text,
    tone text,
    video_generated boolean not null default false,
    created_at timestamptz not null default now()
);

-- Keep anon access closed; the generator uses the service_role key, which
-- bypasses row level security. Add a read policy here if you later want the
-- anon key to read ideas.
alter table public.ideas enable row level security;

create index if not exists ideas_video_generated_idx
    on public.ideas (video_generated, created_at desc);